# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-19 08:58
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_title', models.CharField(max_length=20, verbose_name='商品名称')),
                ('goods_pic', models.ImageField(blank=True, null=True, upload_to='df_goods', verbose_name='商品图片')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('goods_unit', models.CharField(default='500g', max_length=20, verbose_name='商品单位')),
                ('goods_click', models.IntegerField(verbose_name='点击量')),
                ('is_Delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('goods_jianjie', models.CharField(max_length=200, verbose_name='简介')),
                ('goods_kucun', models.IntegerField(verbose_name='库存')),
                ('goods_content', DjangoUeditor.models.UEditorField(verbose_name='详细介绍')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=20, verbose_name='类型名称')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.TypeInfo', verbose_name='所属分类'),
        ),
    ]
