# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-17 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='recv_name',
            field=models.CharField(max_length=20, null=True, verbose_name='收件人'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='you_bian',
            field=models.CharField(default='', max_length=6, verbose_name='邮政编码'),
        ),
    ]
