# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-08 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
